# Generated by Django 3.2.6 on 2021-09-06 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210906_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='title',
            field=models.CharField(choices=[('1', 'user'), ('2', 'admin')], default='admin', max_length=10),
        ),
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('forum_id', models.CharField(max_length=36, primary_key=True, serialize=False, unique=True)),
                ('posted_at', models.DateField(auto_now=True)),
                ('post_title', models.CharField(max_length=150)),
                ('post', models.TextField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.CharField(max_length=36, primary_key=True, serialize=False, unique=True)),
                ('post', models.TextField()),
                ('posted_at', models.DateField(auto_now=True)),
                ('forum_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.forum')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
    ]
